blank_issues_enabled: false
contact_links:
  - name: Ask for help
    url: https://github.com/pungrumpy/gozo/discussions/new?category=help
    about: Need to ask a question? Get help from the community.
  - name: Submit an idea
    url: https://github.com/pungrumpy/gozo/discussions/new?category=ideas
    about: Make feature requests and suggest improvements.
