//! Image build shared by the docker and kubernetes adapters: resolve or
//! generate a Dockerfile, `docker build`, optionally `docker push`.

use std::path::{Path, PathBuf};
use std::process::Command;

use gozo_core::{DockerTarget, STATE_DIR};

use crate::{DeployError, DeployRequest, Reporter, Result, run_capture, run_inherit, which};

/// Where a generated Dockerfile lives, relative to the project root.
pub(crate) const GENERATED_DOCKERFILE: &str = "Dockerfile";

/// Image repository: the configured one, else the sanitized project name.
pub(crate) fn repository(configured: Option<&str>, project: &str) -> String {
    match configured.map(str::trim).filter(|s| !s.is_empty()) {
        Some(c) => c.to_owned(),
        None => sanitize_repo(project),
    }
}

/// Docker repository names must be lowercase `[a-z0-9._-]` path segments.
pub(crate) fn sanitize_repo(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut last_dash = false;
    for c in name.trim().chars() {
        let c = c.to_ascii_lowercase();
        if c.is_ascii_alphanumeric() || c == '.' || c == '/' {
            out.push(c);
            last_dash = false;
        } else if !last_dash && !out.is_empty() {
            out.push('-');
            last_dash = true;
        }
    }
    let out = out.trim_end_matches(['-', '.', '/']).to_owned();
    if out.is_empty() {
        "app".to_owned()
    } else {
        out
    }
}

/// Whether the repository names a registry (`ghcr.io/x`, `localhost:5000/x`).
pub(crate) fn has_registry(repo: &str) -> bool {
    match repo.split_once('/') {
        Some((first, _)) => first.contains('.') || first.contains(':') || first == "localhost",
        None => false,
    }
}

/// Full image reference.
pub(crate) fn image_ref(repo: &str, tag: &str) -> String {
    format!("{repo}:{tag}")
}

/// The Dockerfile that already exists: `cfg.dockerfile`, then `<root>/Dockerfile`.
pub(crate) fn existing_dockerfile(root: &Path, cfg: &DockerTarget) -> Option<PathBuf> {
    if let Some(p) = &cfg.dockerfile {
        let path = root.join(p);
        if path.is_file() {
            return Some(path);
        }
    }
    let default = root.join("Dockerfile");
    if default.is_file() {
        Some(default)
    } else {
        None
    }
}

pub(crate) fn generated_path(root: &Path) -> PathBuf {
    root.join(STATE_DIR).join(GENERATED_DOCKERFILE)
}

pub(crate) fn context_dir(root: &Path, cfg: &DockerTarget) -> PathBuf {
    match &cfg.context {
        Some(c) => root.join(c),
        None => root.to_path_buf(),
    }
}

/// Human description of which Dockerfile a build would use, for preflight.
pub(crate) fn dockerfile_summary(root: &Path, cfg: &DockerTarget) -> (bool, String) {
    match existing_dockerfile(root, cfg) {
        Some(p) => (
            true,
            p.strip_prefix(root).unwrap_or(&p).display().to_string(),
        ),
        None => (
            true,
            format!(
                "none found, will generate {}/{}",
                STATE_DIR, GENERATED_DOCKERFILE
            ),
        ),
    }
}

/// The package `go build` should compile. `./cmd/<project>` when it exists,
/// else the only package under `cmd/`, else `.` when a root `main.go` exists.
pub(crate) fn main_package(root: &Path, project: &str) -> String {
    let cmd = root.join("cmd");
    if cmd.join(project).join("main.go").is_file() {
        return format!("./cmd/{project}");
    }
    let mut candidates: Vec<String> = std::fs::read_dir(&cmd)
        .map(|rd| {
            rd.filter_map(|e| e.ok())
                .filter(|e| e.path().join("main.go").is_file())
                .map(|e| e.file_name().to_string_lossy().into_owned())
                .collect()
        })
        .unwrap_or_default();
    candidates.sort();
    match candidates.as_slice() {
        [only] => format!("./cmd/{only}"),
        [] if root.join("main.go").is_file() => ".".to_owned(),
        _ => format!("./cmd/{project}"),
    }
}

/// A multi-stage Dockerfile for a Go service. `workspace` skips the
/// `go mod download` layer, which needs a single go.mod at the context root.
pub(crate) fn generate_dockerfile(main_pkg: &str, workspace: bool) -> String {
    let deps = if workspace {
        "COPY . .\n"
    } else {
        "COPY go.mod go.sum* ./\nRUN go mod download\nCOPY . .\n"
    };
    format!(
        "# syntax=docker/dockerfile:1
# Generated by gozo. Move this file to ./Dockerfile to take ownership of it.
FROM golang:1.27 AS build
WORKDIR /src
{deps}RUN CGO_ENABLED=0 go build -trimpath -ldflags \"-s -w\" -o /out/app {main_pkg}

FROM gcr.io/distroless/static-debian12
COPY --from=build /out/app /app
ENTRYPOINT [\"/app\"]
"
    )
}

/// Resolve the Dockerfile for a build, generating one when none exists.
pub(crate) fn ensure_dockerfile(
    root: &Path,
    project: &str,
    cfg: &DockerTarget,
    r: &mut dyn Reporter,
) -> Result<PathBuf> {
    if let Some(p) = existing_dockerfile(root, cfg) {
        return Ok(p);
    }
    let path = generated_path(root);
    let main_pkg = main_package(root, project);
    let workspace = root.join("go.work").is_file();
    let text = generate_dockerfile(&main_pkg, workspace);
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir)?;
    }
    std::fs::write(&path, text)?;
    r.step(&format!(
        "No Dockerfile found, generated {}/{} (builds {})",
        STATE_DIR, GENERATED_DOCKERFILE, main_pkg
    ));
    if !dockerignore_excludes_state(root) {
        r.warn(&format!(
            "add `{STATE_DIR}` to .dockerignore so local env files never end up in the image"
        ));
    }
    Ok(path)
}

fn dockerignore_excludes_state(root: &Path) -> bool {
    std::fs::read_to_string(root.join(".dockerignore"))
        .map(|t| {
            t.lines().map(str::trim).any(|l| {
                l == STATE_DIR || l == format!("{STATE_DIR}/") || l == format!("/{STATE_DIR}")
            })
        })
        .unwrap_or(false)
}

/// `docker build` the image for `req`, then `docker push` when asked.
/// A dry run still builds but never pushes.
pub(crate) fn build(
    root: &Path,
    project: &str,
    cfg: &DockerTarget,
    image: &str,
    req: &DeployRequest,
    push: bool,
    r: &mut dyn Reporter,
) -> Result<()> {
    if !which("docker") {
        return Err(DeployError::ToolMissing { tool: "docker" });
    }
    let dockerfile = ensure_dockerfile(root, project, cfg, r)?;
    let context = context_dir(root, cfg);
    if !context.is_dir() {
        return Err(DeployError::Config(format!(
            "build context {} does not exist",
            context.display()
        )));
    }

    r.step(&format!("Building {image}"));
    let mut cmd = Command::new("docker");
    cmd.arg("build");
    if let Some(p) = &cfg.platform {
        cmd.args(["--platform", p]);
    }
    if req.force {
        cmd.arg("--no-cache");
    }
    for (k, v) in &req.build_env {
        cmd.arg("--build-arg").arg(format!("{k}={v}"));
    }
    cmd.args(["-t", image, "-f"]).arg(&dockerfile).arg(&context);
    if req.verbose {
        run_inherit(cmd, r)?;
    } else {
        run_capture(cmd, r)?;
    }

    if push {
        if req.dry_run {
            r.detail(&format!("dry run: not pushing {image}"));
        } else {
            push_image(image, req.verbose, r)?;
        }
    }
    Ok(())
}

pub(crate) fn push_image(image: &str, verbose: bool, r: &mut dyn Reporter) -> Result<()> {
    r.step(&format!("Pushing {image}"));
    let mut cmd = Command::new("docker");
    cmd.args(["push", image]);
    if verbose {
        run_inherit(cmd, r)
    } else {
        run_capture(cmd, r).map(|_| ())
    }
}

/// Run a probe command and return its trimmed stdout, or a one-line reason.
pub(crate) fn probe(mut cmd: Command, r: &mut dyn Reporter) -> std::result::Result<String, String> {
    r.command(&crate::format_command(&cmd));
    let out = match cmd.output() {
        Ok(o) => o,
        Err(e) => return Err(e.to_string()),
    };
    let stdout = String::from_utf8_lossy(&out.stdout).trim().to_owned();
    if out.status.success() {
        return Ok(stdout);
    }
    let stderr = String::from_utf8_lossy(&out.stderr);
    let line = stderr
        .lines()
        .chain(stdout.lines())
        .map(str::trim)
        .find(|l| !l.is_empty())
        .map(str::to_owned)
        .unwrap_or_else(|| format!("exit code {}", out.status.code().unwrap_or(-1)));
    Err(line)
}

/// Preflight entries shared by every adapter that builds with docker.
pub(crate) fn docker_checks(r: &mut dyn Reporter) -> Vec<(String, bool, String)> {
    let mut out = Vec::new();
    if !which("docker") {
        out.push((
            "docker".to_owned(),
            false,
            "not found on PATH; install Docker Desktop or docker-ce".to_owned(),
        ));
        return out;
    }
    let mut cmd = Command::new("docker");
    cmd.args(["version", "--format", "{{.Client.Version}}"]);
    match probe(cmd, r) {
        Ok(v) => out.push(("docker".to_owned(), true, v)),
        Err(e) => {
            out.push(("docker".to_owned(), false, e));
            return out;
        }
    }
    let mut cmd = Command::new("docker");
    cmd.args(["info", "--format", "{{.ServerVersion}}"]);
    match probe(cmd, r) {
        Ok(v) => out.push(("docker daemon".to_owned(), true, format!("server {v}"))),
        Err(e) => out.push((
            "docker daemon".to_owned(),
            false,
            format!("{e} (is Docker running?)"),
        )),
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A unique scratch directory, removed on drop (this crate has no temp-dir dependency).
    struct Scratch(PathBuf);
    impl Scratch {
        fn new(tag: &str) -> Self {
            let nanos = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0);
            let dir = std::env::temp_dir().join(format!(
                "gozo-image-test-{tag}-{}-{nanos}",
                std::process::id()
            ));
            std::fs::create_dir_all(&dir).unwrap();
            Scratch(dir)
        }
        fn path(&self) -> &Path {
            &self.0
        }
    }
    impl Drop for Scratch {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn repository_defaults_to_sanitized_project() {
        assert_eq!(repository(None, "My_App"), "my-app");
        assert_eq!(repository(Some(""), "x"), "x");
        assert_eq!(
            repository(Some("ghcr.io/acme/api"), "x"),
            "ghcr.io/acme/api"
        );
        assert_eq!(sanitize_repo("Hello World!!"), "hello-world");
        assert_eq!(sanitize_repo("---"), "app");
        assert_eq!(sanitize_repo("acme/API.v2"), "acme/api.v2");
    }

    #[test]
    fn registry_detection() {
        assert!(has_registry("ghcr.io/acme/api"));
        assert!(has_registry("localhost:5000/api"));
        assert!(has_registry("registry:5000/api"));
        assert!(!has_registry("acme/api"));
        assert!(!has_registry("api"));
    }

    #[test]
    fn dockerfile_generation() {
        let d = generate_dockerfile("./cmd/hello", false);
        assert!(d.starts_with("# syntax=docker/dockerfile:1\n"));
        assert!(d.contains("FROM golang:1.27 AS build\n"));
        assert!(d.contains("COPY go.mod go.sum* ./\nRUN go mod download\n"));
        assert!(d.contains(
            "RUN CGO_ENABLED=0 go build -trimpath -ldflags \"-s -w\" -o /out/app ./cmd/hello\n"
        ));
        assert!(d.contains("FROM gcr.io/distroless/static-debian12\n"));
        assert!(d.contains("COPY --from=build /out/app /app\n"));
        assert!(d.ends_with("ENTRYPOINT [\"/app\"]\n"));

        let w = generate_dockerfile(".", true);
        assert!(!w.contains("go mod download"));
        assert!(w.contains("-o /out/app .\n"));
    }

    #[test]
    fn main_package_detection() {
        let dir = Scratch::new("main");
        let root = dir.path();
        // nothing: falls back to ./cmd/<project>
        assert_eq!(main_package(root, "svc"), "./cmd/svc");
        // a single cmd package wins
        std::fs::create_dir_all(root.join("cmd/worker")).unwrap();
        std::fs::write(root.join("cmd/worker/main.go"), "package main").unwrap();
        assert_eq!(main_package(root, "svc"), "./cmd/worker");
        // several: prefer the one named after the project
        std::fs::create_dir_all(root.join("cmd/svc")).unwrap();
        std::fs::write(root.join("cmd/svc/main.go"), "package main").unwrap();
        assert_eq!(main_package(root, "svc"), "./cmd/svc");
        // several without a match: fall back to ./cmd/<project>
        assert_eq!(main_package(root, "other"), "./cmd/other");
        // root main.go only
        let dir2 = Scratch::new("root");
        std::fs::write(dir2.path().join("main.go"), "package main").unwrap();
        assert_eq!(main_package(dir2.path(), "svc"), ".");
    }

    #[test]
    fn existing_dockerfile_precedence() {
        let dir = Scratch::new("dockerfile");
        let root = dir.path();
        let mut cfg = DockerTarget::default();
        assert!(existing_dockerfile(root, &cfg).is_none());
        std::fs::write(root.join("Dockerfile"), "FROM scratch").unwrap();
        assert_eq!(
            existing_dockerfile(root, &cfg),
            Some(root.join("Dockerfile"))
        );
        cfg.dockerfile = Some("build/Dockerfile.prod".into());
        // configured but missing: fall back to ./Dockerfile
        assert_eq!(
            existing_dockerfile(root, &cfg),
            Some(root.join("Dockerfile"))
        );
        std::fs::create_dir_all(root.join("build")).unwrap();
        std::fs::write(root.join("build/Dockerfile.prod"), "FROM scratch").unwrap();
        assert_eq!(
            existing_dockerfile(root, &cfg),
            Some(root.join("build/Dockerfile.prod"))
        );
    }
}
