#!/usr/bin/env node
// Publishes the packages generated by package-native.mjs. Versions already on
// the registry are skipped, so re-running a failed release is safe.
import { spawnSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const dir = path.resolve(process.argv[2] ?? "packages/gozo/npm");
if (!existsSync(dir)) {
  console.error(
    `publish-native: ${dir} does not exist; run scripts/package-native.mjs first`
  );
  process.exit(1);
}

/* oxlint-disable sonarjs/no-os-command-from-path -- npm comes from the runner's PATH */
const npm = (args, options = {}) =>
  spawnSync("npm", args, { encoding: "utf-8", ...options });
/* oxlint-enable sonarjs/no-os-command-from-path */

const isPublished = (spec) => {
  const view = npm(["view", spec, "version", "--json"]);
  return (
    view.status === 0 &&
    view.stdout.trim() !== "" &&
    !view.stdout.includes("E404")
  );
};

const readManifest = (name) => {
  const manifestPath = path.join(dir, name, "package.json");
  if (!existsSync(manifestPath)) {
    return null;
  }
  const { name: packageName, version } = JSON.parse(
    readFileSync(manifestPath, "utf-8")
  );
  return { dir: path.join(dir, name), spec: `${packageName}@${version}` };
};

const publish = (manifest) => {
  if (isPublished(manifest.spec)) {
    console.log(`${manifest.spec} already on the registry, skipping`);
    return false;
  }
  console.log(`publishing ${manifest.spec}`);
  const result = npm(["publish", "--provenance", "--access", "public"], {
    cwd: manifest.dir,
    stdio: "inherit",
  });
  if (result.status !== 0) {
    throw new Error(
      `npm publish failed for ${manifest.spec} (exit ${result.status ?? "unknown"})`
    );
  }
  return true;
};

let published = 0;
for (const name of readdirSync(dir)) {
  const manifest = readManifest(name);
  if (manifest && publish(manifest)) {
    published += 1;
  }
}
console.log(
  `publish-native: ${published} package(s) published from ${path.relative(root, dir)}`
);
